name = "pulseflare-checker"
main = "src/index.ts"
compatibility_date = "2026-05-06"

[triggers]
crons = ["*/1 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "pulseflare"
database_id = "8c45da35-ca25-449d-b336-3fe2f96efb49"

[[kv_namespaces]]
binding = "STATUS_KV"
id = "b5a81e5554bd4386b77f018c6d34a972"

[[queues.producers]]
binding = "INCIDENT_QUEUE"
queue = "incident-events"

[[queues.producers]]
binding = "ALERT_QUEUE"
queue = "alert-events"
