name = "pulseflare-ai"
account_id = "f456997005771d4af03fa8f845a54f62"
main = "src/index.ts"
compatibility_date = "2026-05-06"

[[d1_databases]]
binding = "DB"
database_name = "pulseflare"
database_id = "3136547a-66dd-484b-b931-06f04564f635"

[[queues.consumers]]
queue = "incident-events"
max_batch_size = 10
max_batch_timeout = 30

[[queues.producers]]
binding = "ALERT_QUEUE"
queue = "alert-events"

[ai]
binding = "AI"
